### ISSUE TITLE
weather_forecasting2018_eval.py

### ISSUE THREAD

**Issue by longzuxiaotian** [AIChallenger/AI_Challenger_2018#11]
parser.add_argument(
        '--ref',
        type=str,
        default='./ans.csv',                      -----------------     ‘./obs.csv’
        help="""
                Path to reference file
            """
    )

    parser.add_argument(
        '--anen',
        type=str,
        default='./ans.csv',                      -----------------      './anen.csv'
        help="""
                    Path to anen file
                """
    )
    态度要端正

**Comment by awyd234** [comment]
ok, we have fixed it, now you can pull the latest edition

**Comment by longzuxiaotian** [comment]
good job
