### ISSUE TITLE
The submission format for English and Chinese translation is incorrect

### ISSUE THREAD

**Issue by lijun20** [AIChallenger/AI_Challenger_2018#9]
Are there any specific examples submitted ？

**Comment by awyd234** [comment]
hi, sample submission and evaluation script have uploaded now, you can refer to [https://github.com/AIChallenger/AI_Challenger_2018/tree/master/Evaluation/english_chinese_machine_translation2018_eval](https://github.com/AIChallenger/AI_Challenger_2018/tree/master/Evaluation/english_chinese_machine_translation2018_eval)
